### ISSUE TITLE
清理文件夹插件 clean-webpack-plugin 使用方法问题

### ISSUE THREAD

**Issue by L924553229** [webpack-china/webpack.js.org#1060]
https://www.webpackjs.com/guides/output-management/ 中清理文件夹插件 clean-webpack-plugin, 使用方法是否应该为:
`
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
new CleanWebpackPlugin()
`

**Comment by QC-L** [comment]
不好意思哈，请你仔细看看仓库的文档地址是啥~
你看的是盗版的哦，谢谢~
