### ISSUE TITLE
webpack中文文档没有更新

### ISSUE THREAD

**Issue by horizon188** [webpack-china/webpack.js.org#1093]
**https://www.webpackjs.com/guides/ Document content is missing, content is old**

**Please update，thanks**

**Comment by KimYangOfCat** [comment]
> **https://www.webpackjs.com/guides/ Document content is missing, content is old**
> 
> **Please update，thanks**

抱歉，你访问的是盗用我们仓库翻译的盗版文档，正版最新文档，请访问：https://webpack.docschina.org/ 
请认准 docschina.org 域名
