### ISSUE TITLE
英文官网跳转链接错误

### ISSUE THREAD

**Issue by CesarLai** [webpack-china/webpack.js.org#1676]
webpack 中文官网顶部的 **英文官网** 链接无法正常跳转，其跳转地址为：

/https://webpack.js.org//

实际应该是：
https://webpack.js.org/

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23397937/189586934-ca1301e0-538d-458e-aeb1-2f2ae0c45aa7.png">

**Comment by jacob-lcs** [comment]
我们的官方地址是：https://webpack.docschina.org/
