### ISSUE TITLE
content/plugins/html-webpack-plugin.md

### ISSUE THREAD

**Issue by lgh06** [webpack-china/webpack.js.org#185]
类似这个路径的markdown 不需要认领么…… 或者说这个是近期更新的 之前没有生成issue……

**Comment by lgh06** [comment]
Project中也没有这一条…… 看起来像近期加的……？

**Comment by lcxfs1991** [comment]
@lgh06 后续还有一些新增加的插件需要认领，等我们先把concepts和guides校对好。

**Comment by lgh06** [comment]
收到。
