### ISSUE TITLE
英文版的单个markdown上面的contributor都是手工打上去的么……

### ISSUE THREAD

**Issue by lgh06** [webpack-china/webpack.js.org#189]
有没有可能是扫描历史commit记录 自动添加的。
同理，对比官方整个的commit历史和cn分支的commit历史 是不是也可以得出中文版的整个的contributors

**Comment by lcxfs1991** [comment]
现在是手工，历史commit，也包含了官方的那些commit，难以分辨。除非加个标记。

**Comment by dear-lizhihua** [comment]
我是倾向于保留原始文档，所以不太希望和官方的混合在一起，现在单独放在一个markdown里面了，入口在导航。
