### ISSUE TITLE
/content/guides/code-splitting-import

### ISSUE THREAD

**Issue by lcxfs1991** [webpack-china/webpack.js.org#218]
1. Check the existing issues to see if you can find something matching to your request.
2. If you didn't find a relevant issue, go ahead and open a new one. It's better to make small typo fixes and such directly as pull requests.

**Comment by LeoEatle** [comment]
我翻译这个，3-15——3-20

**Comment by Aladdin-ADD** [comment]
认领校对：此章节由我校对。 时间  2017.03.23~2017.03.25

**Comment by Aladdin-ADD** [comment]
校对完成. #227

**Comment by dear-lizhihua** [comment]
此文档已合并为/content/guides/code-splitting-async.md，需要重新翻译，故关闭此 issue。
