### ISSUE TITLE
【提议】简单排版（空格，换行，中英文标点）自动化检查

### ISSUE THREAD

**Issue by Aladdin-ADD** [webpack-china/webpack.js.org#224]
很多微小的问题都可以自动化检查，包括&不限于（空格，换行，中英文标点），能不能用脚本处理这些问题，提交之前给贡献者提醒？或者有现成可用的工具？

**Comment by dear-lizhihua** [comment]
最好有具体的思路啊。会涉及到开源项目投入的成本和回报，毕竟都是业余时间在翻译。
