### ISSUE TITLE
[反馈/官网] 中文文档站左侧目录在页面滚动时定位错误遮挡横向导航

### ISSUE THREAD

**Issue by JayceZhang9602** [webpack-china/webpack.js.org#229]
### 问题描述
中文文档站左侧目录展开至一定高度后，在页面滚动时定位错误， 遮挡横向导航，详见截图

### 操作系统/浏览器 版本号
macOS 10.12.3/Chrome 56
windows 10/Chrome 56

### 问题在线复原地址
https://docs.webpack-china.org/configuration/

### 复现步骤
页面往下滚动约40px

### 截图
macOS
<img width="1437" alt="screen shot 2017-03-28 at 10 07 51 pm" src="https://cloud.githubusercontent.com/assets/20334140/24409862/0d9e10ac-1404-11e7-92b9-119d896f2456.png">

windows
![qq 20170328221707](https://cloud.githubusercontent.com/assets/20334140/24410047/9b25a890-1404-11e7-8f0f-c4680c9214d9.png)

**Comment by dear-lizhihua** [comment]
这是官方样式的问题，我们的仓库只负责翻译。
拉取项目本地运行后也有这个问题吗？如果有的话建议去官方提 issue，让他们修复 bug。没有的话说明官方已经修复了这个问题，只不过我们线上没有及时构建站点。

**Comment by JayceZhang9602** [comment]
https://webpack.js.org/ 没有这个bug，可能是已经修复了

**Comment by dear-lizhihua** [comment]
那就应该没问题了，我们的官网上次构建好像是1、2月的时候。
