### ISSUE TITLE
[ci]The command "bash ./scripts/deploy.sh" exited with 1.

### ISSUE THREAD

**Issue by Aladdin-ADD** [webpack-china/webpack.js.org#249]
linking https://travis-ci.org/webpack-china/webpack.js.org/jobs/222592871

**Comment by lcxfs1991** [comment]
今天看下

**Comment by lcxfs1991** [comment]
我暂时先把那个markdown lint去掉，看看行不行

**Comment by Aladdin-ADD** [comment]
把`eslint *.md`也去掉吧。
https://github.com/webpack/webpack.js.org/issues/1041

**Comment by Aladdin-ADD** [comment]
resolved, closing.
