### ISSUE TITLE
/content/guides/code-splitting-async.md

### ISSUE THREAD

**Issue by dear-lizhihua** [webpack-china/webpack.js.org#264]
Code Splitting - Async
合并自
#49 /content/guides/code-splitting-require.md
#218 /content/guides/code-splitting-import.md

**Comment by dear-lizhihua** [comment]
此章节由我翻译，翻译时间为 2017.05.11-2017.05.25。

**Comment by dear-lizhihua** [comment]
https://github.com/webpack-china/webpack.js.org/commit/bfd176f5f5da4a6cb3d8349dc3f721ddce33796e

忘了自己是 master 权限了，本来想直接编辑完提 pr 的。大家帮忙校对下吧。
@mc-zone @LeoEatle

**Comment by Aladdin-ADD** [comment]
LGTM.

**Comment by dear-lizhihua** [comment]
已合并至 #147，本 issue 关闭
