### ISSUE TITLE
关于翻译认领

### ISSUE THREAD

**Issue by Jabinzou** [webpack-china/webpack.js.org#28]
您好，怎么才能认领任务呢？

**Comment by dear-lizhihua** [comment]
看下这里：#17

**Comment by Jabinzou** [comment]
ok

**Comment by dear-lizhihua** [comment]
### 加入微信群
为了加速 webpack 的推广，我们决定建立一个 webpack 中文翻译的微信群，大家在里面可以互相交流。
大家先添加我的微信号 wuwangbufu002，加的时候报下你的 github 名称，我将加你好友，然后拉入微信群。
