### ISSUE TITLE
/content/api/plugins.md

### ISSUE THREAD

**Issue by dear-lizhihua** [webpack-china/webpack.js.org#33]
Plugin API

**Comment by daxianyu** [comment]
此章节由我翻译，翻译时间为 2017.01.21-2017.02.01

**Comment by dear-lizhihua** [comment]
这篇现在官方还没写好啊。

**Comment by daxianyu** [comment]
我本来打算先认领再去翻译。。。刚刚看到。。。那我换个

**Comment by dear-lizhihua** [comment]
我建了一个微信群，把你拉进去，我微信号 wuwangbufu002，加的时候报下名字。

**Comment by mc-zone** [comment]
此文章由我翻译，翻译时间2017.01.30-2017.02.03

**Comment by dear-lizhihua** [comment]
@jeffrygan @mc-zone 
#33 /content/api/plugins.md 和 #5 /content/api/plugins/index.md 合并
