### ISSUE TITLE
指南中缓存这块文章中提到ChunkManifestWebpackPlugin插件貌似不兼容

### ISSUE THREAD

**Issue by GoDotDotDot** [webpack-china/webpack.js.org#339]
在指南模块下的缓存文章中[确定性的(Deterministic)哈希值
](https://doc.webpack-china.org/guides/caching/)这块，文章中提到`ChunkManifestWebpackPlugin`插件，但是经测试，在Webpack 3版本中出现错误：
```javascript
ERROR in chunk manifest [entry]
js/[name].bundle.js
Chunk.entry was removed. Use hasRuntime()
```
貌似是不兼容的情况。 

reference：[Error in chunk manifest[entry]](https://github.com/soundcloud/chunk-manifest-webpack-plugin/issues/45)

**Comment by dear-lizhihua** [comment]
感谢指出，中文仓库只负责翻译英文仓库，最好还是去官方[英文仓库](https://github.com/webpack/webpack.js.org)提 issue，这样我们在合并上游文档的过程中会重新翻译。

**Comment by dear-lizhihua** [comment]
@GoDotDotDot 帮你看了下，https://webpack.js.org/guides/caching/ 英文文档已经搜索不到 ChunkManifestWebpackPlugin 这个关键词，估计是重新编写了，官方文档的改动还是挺频繁的。

**Comment by GoDotDotDot** [comment]
@dear-lizhihua  发现问题后我就去英文官网看了下，发现更新了，然后就按照英文官网的说明去配置的，已经解决。我去了[ERROR in chunk manifest [entry] with webpack v3.1.0](https://github.com/webpack/webpack/issues/5368) 这个地方提了issue。回应的是ChunkManifestWebpackPlugin这个插件兼容性有问题

**Comment by dear-lizhihua** [comment]
OK，那我关闭了
