### ISSUE TITLE
alias处有翻译错误

### ISSUE THREAD

**Issue by sqfbeijing** [webpack-china/webpack.js.org#410]
原文：
```
import Test1 from 'xyz'; // Exact match, so path/to/file.js is resolved and imported
import Test2 from 'xyz/file.js'; // Not an exact match, normal resolution takes place
```
翻译：
```
import Test1 from 'xyz'; // 精确匹配，所以 path/to/file.js 被解析和导入
import Test2 from 'xyz/file.js'; // 精确匹配，触发普通解析
```

import Test2 from 'xyz/file.js'; //   应该是非精确匹配。
[链接1](https://webpack.js.org/configuration/resolve/)
[链接2](https://doc.webpack-china.org/configuration/resolve//)

**Comment by dear-lizhihua** [comment]
感谢指出，直接提 pr 就行

**Comment by dear-lizhihua** [comment]
https://github.com/webpack-china/webpack.js.org/commit/6c93d94b182c7c04d994dc4daf9e2a6a2a3cf510#diff-6dd9a1b57e5747d8e346b2834f34f8af
此节点合并上游分支时导致
