### ISSUE TITLE
there is an error （module not found :Error:can't resolve './starter-kits-data.json'） when i npm start

### ISSUE THREAD

**Issue by cb288** [webpack-china/webpack.js.org#432]
when i check the files ，has not a file named starter-kits-data.json

**Comment by lcxfs1991** [comment]
@cb288 你QQ或者微信多少，加你沟通？

**Comment by dear-lizhihua** [comment]
npm start 里面包含 npm run fetch，可能需要开启代理，拉取 support-backers.json 和 starter-kits-data.json

**Comment by cb288** [comment]
@lcxfs1991 qq 362258983

**Comment by cb288** [comment]
@dear-lizhihua npm start中依赖别的脚本，Linux环境下才能运行吗？windows不好使。
