### ISSUE TITLE
文档中遇到的问题

### ISSUE THREAD

**Issue by jiangruiqi** [webpack-china/webpack.js.org#804]
在webpack中文文档-指南-管理输出-清理/dist文件夹文章中，
执行yarn add --dev clean-webpack-plugin，安装的依赖版本为3.0.0，
webpack.config.js中

+ const CleanWebpackPlugin = require('clean-webpack-plugin');
+     new CleanWebpackPlugin(['dist']),

会报错    Error: clean-webpack-plugin only accepts an options object.
需要以下方式引用
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

**Comment by QC-L** [comment]
我们文档是正常的啊，访问地址 [管理输出](https://webpack.docschina.org/guides/output-management/#%E6%B8%85%E7%90%86-dist-%E6%96%87%E4%BB%B6%E5%A4%B9)
