### ISSUE TITLE
Display Problem on Chinese AssetManagement Website

### ISSUE THREAD

**Issue by Ji4ming** [webpack-china/webpack.js.org#809]
https://www.webpackjs.com/guides/asset-management/

https://github.com/docschina/webpack.js.org/blob/cn/src/content/guides/asset-management.md

The change from main.js to bundle.js(line 35-36) is not truly highlighted on the webpage which may lead to certain misunderstandings or omissions.

This change is supposed to be highlighted as it is crucial for all the changes we will make in latter sections.

**Comment by QC-L** [comment]
webpackjs.com 并不是官网，官网是 webpack.js.org，不要被百度误导。webpackjs.com 上的文章很久了

**Comment by chenxsan** [comment]
@QC-L 查了下网站备案，webpackjs 域名似乎不是你们持有？

**Comment by QC-L** [comment]
@chenxsan 是的，他 copy 的我们的内容，极其恶劣，还被百度标为了官网。欸，没办法
