### ISSUE TITLE
【文档错误】中文文档指南模块，生产环境搭建中merge引入方式

### ISSUE THREAD

**Issue by chen-jiajian** [webpack-china/webpack.js.org#826]
中文文档指南模块，生产环境搭建步骤，webpack.dev.js和webpack.prod.js中的merge引入，文档中为：
`const merge = require('webpack-merge')`, 会报错 merge is no function， 更改引入方式为`const {merge} = require('webpack-merge')` 解决

**Comment by QC-L** [comment]
我查了下，文档没有问题。
目前来看是构建时产生的缓存问题，我们查一下，稍后给出原因。

**Comment by QC-L** [comment]
已修复
