### ISSUE TITLE
[文档错误][Tree Shaking]翻译有语法错误...

### ISSUE THREAD

**Issue by sy0uta1k0n** [webpack-china/webpack.js.org#828]
__Feature to document__

tree shaking: https://webpack.docschina.org/guides/tree-shaking/

原文: <这样会允许去掉这代码代码，但仍然会有一些导入的问题需要被包括/评估，因为它们包含了副作用。>
应为: <这样会允许去掉这段代码，但仍然会有一些导入的问题需要被包括/评估，因为它们包含了副作用。>

__Additional information__

<img width="1115" alt="tree shaking" src="https://user-images.githubusercontent.com/13308844/89142828-0fbd9d80-d57b-11ea-86e3-7741d6db7aff.png">

[Y] I am willing to work on this issue and submit a pull request.

**Comment by QC-L** [comment]
提个 pr 就 okay 的，可能笔误带上去的

**Comment by QC-L** [comment]
已修复

**Comment by QC-L** [comment]
https://github.com/docschina/webpack.js.org/commit/1e8a0f6a400cede3a8a42b02af4000ef0343edfd
