### ISSUE TITLE
生产环境构建

### ISSUE THREAD

**Issue by gideonsenku** [webpack-china/webpack.js.org#832]
![image](https://user-images.githubusercontent.com/39037656/89873750-7f700000-dbed-11ea-9deb-805bf1eb89be.png)

> 编辑此页时，显示的和英文文档一样的解构赋值，不知道为何此处还未更改。请求修复该问题

**Comment by QC-L** [comment]
应该是构建的问题，我们抽空刷新下

**Comment by QC-L** [comment]
已修复
