### ISSUE TITLE
webpack在线中文文档【管理输出】章节和当前项目readme文件未同步更新

### ISSUE THREAD

**Issue by 827652549** [webpack-china/webpack.js.org#850]
发现了github上的md文档和在线webpack文档不对应的问题。

https://www.webpackjs.com/guides/output-management/#%E6%B8%85%E7%90%86-dist-%E6%96%87%E4%BB%B6%E5%A4%B9
关于清理dist文件夹，在线文档的推荐clean-webpack-plugin进行操作，

当前clean-webpack-plugin的引入方式应该是
```
const {CleanWebpackPlugin} = require('clean-webpack-plugin');
```
但在线文档还是通过旧的

```
import CleanWebpackPlugin = require('clean-webpack-plugin');
```

于是我点开“编辑此页”，准备pr一下这个docs，但是意外地发现，源markdown文档已经改变了（最后修改时间已经超过1个月），只是在线官网没有同步更新，希望这个部门能修改一下。

**Comment by QC-L** [comment]
不好意思，你看的是盗版网站。

@827652549

真正的网站如下:

[webpack 官方中文文档](https://webpack.docschina.org)

**Comment by justjavac** [comment]
@827652549 我建议你先举报这个网站，然后到真正的中文官方去看文档

**Comment by 827652549** [comment]
🤦‍♂️我是个憨憨，谢谢各位
