### ISSUE TITLE
[文档错误]配置页中的Rule.options / Rule.query与英文文档不一致

### ISSUE THREAD

**Issue by Clarkkkk** [webpack-china/webpack.js.org#860]
中文文档：https://webpack.docschina.org/configuration/module/#ruleoptions--rulequery

> 由于需要支持 Rule.options 和 UseEntry.options，Rule.use，Rule.query 已废弃。

英文文档：https://webpack.js.org/configuration/module/#ruleoptions--rulequery

> Rule.query is deprecated in favor of Rule.options and UseEntry.options.

Rule.use 并未废弃，需要修正。

**Comment by QC-L** [comment]
是 Rule.query 废弃了，这里表达有些问题，我调整下。

**Comment by QC-L** [comment]
在 https://github.com/docschina/webpack.js.org/pull/859 修复了~
