### ISSUE TITLE
Webpack起步demo中的bug

### ISSUE THREAD

**Issue by StevenX911** [webpack-china/webpack.js.org#887]
具体位置：
中文文档：https://www.webpackjs.com/guides/getting-started/
**index.html**
```html
<!doctype html>
<html>
  <head>
    <title>起步</title>
    <script src="https://unpkg.com/lodash@4.16.6"></script>
  </head>
  <body>
    <script src="./src/index.js"></script>
  </body>
</html>
```
文档中加载js时未设置`charset="utf-8"`，这会导致webpack编译后的js存在编码问题，浏览器无法解析正确！！！
![image](https://user-images.githubusercontent.com/7801675/99146878-249be800-26b7-11eb-8c2f-51b5376ae310.png)

#### 解决方案
增加编码声明，共有两种方式：
1. 在script标签中增加charset属性：`<script src="./main.js" charset="utf-8"></script>`
2. 在head标签中增加meta元素指定charset：` <meta charset="utf-8" />`

英文文档：https://webpack.js.org/guides/getting-started/
`已解决`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Getting Started</title>
    <script src="https://unpkg.com/lodash@4.17.20"></script>
  </head>
  <body>
    <script src="./src/index.js"></script>
  </body>
</html>
```

**Comment by QC-L** [comment]
不好意思，你看的文档不是我们的文档，webpackjs.com 是个盗版网站，我们的站点是 [https://webpack.docschina.org](https://webpack.docschina.org)，并且我们只有这一个站点

**Comment by StevenX911** [comment]
> 不好意思，你看的文档不是我们的文档，webpackjs.com 是个盗版网站，我们的站点是 https://webpack.docschina.org，并且我们只有这一个站点

好的，多谢指正，贵站还需要提升下SEO的权重啊，😂
![image](https://user-images.githubusercontent.com/7801675/99210570-1659e300-2801-11eb-86c1-53be0ab23761.png)

![image](https://user-images.githubusercontent.com/7801675/99210576-1fe34b00-2801-11eb-8af9-3973cbabc370.png)

**Comment by QC-L** [comment]
和权重没关系，你可以去看看他网站的 SEO，非常的无赖。并且他网站也是 copy 的我们。

**Comment by Volcano-Yang** [comment]
这个盗版网站真的让人生气😠   在这个盗版网站发现一处语法错误，想要更新修改的，发现源码是正确的，但是网站页面是错误的。看了一下closed的issue才发现他们是盗版。

![image](https://user-images.githubusercontent.com/43328103/102713450-47976880-4303-11eb-8232-b73afe5dc20c.png)

![image](https://user-images.githubusercontent.com/43328103/102713451-4bc38600-4303-11eb-8dd7-fdfd16081da6.png)

**Comment by Volcano-Yang** [comment]
修改收藏链接了 支持正版
